name: Tariqak
options:
  deploymentTarget:
    iOS: "17.0"
  bundleIdPrefix: com.example

targets:
  Tariqak:
    type: application
    platform: iOS
    sources:
      - Models
      - Services  
      - ViewModels
      - Views
      - path: .
        includes:
          - TariqakApp.swift
    info:
      path: Config/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.tariqak
        SWIFT_VERSION: 5.9
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: "Tariqak"  
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
      configurations:
        Debug:
          HERE_API_KEY: $(HERE_API_KEY)
        Release:
          HERE_API_KEY: $(HERE_API_KEY)
    configFiles:
      Debug: Config/Secrets.xcconfig
      Release: Config/Secrets.xcconfig
