name: Tariqak
options:
  deploymentTarget:
    iOS: "17.0"

targets:
  Tariqak:
    type: application
    platform: iOS
    sources:
      - Models
      - Services  
      - ViewModels
      - Views
      - TariqakApp.swift
    info:
      path: Config/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.tariqak
      SWIFT_VERSION: 5.9
      HERE_API_KEY: "$(HERE_API_KEY)"
