name: iOS Simulator Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Homebrew (if needed)
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Create Secrets.xcconfig from repo secret
        run: |
          mkdir -p Config
          echo "HERE_API_KEY = ${{ secrets.HERE_API_KEY }}" > Config/Secrets.xcconfig

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Select latest Xcode on this runner
        run: |
          echo "Installed Xcodes:"
          ls -1 /Applications | grep Xcode || true
          # جرّب اختيار Xcode 16 إن وجد، وإلا يرجع لـ 15.4
          sudo xcode-select -s /Applications/Xcode_16.app || sudo xcode-select -s /Applications/Xcode_15.4.app
          xcodebuild -version

      - name: Build for iOS Simulator (Debug)
        run: |
          set -e
          xcodebuild \
            -project Tariqak.xcodeproj \
            -scheme Tariqak \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build \
            build

      - name: Package .app as zip
        run: |
          set -e
          echo "Listing possible products..."
          find build -maxdepth 4 -type d -name "*.app" -print || true
          APP_PATH=$(find build -type d -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "No .app found. Check previous step logs."
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          cd "$(dirname "$APP_PATH")"
          zip -r Tariqak-Simulator.zip "$(basename "$APP_PATH")"
          mv Tariqak-Simulator.zip "$GITHUB_WORKSPACE"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tariqak-Simulator
          path: Tariqak-Simulator.zip
